---
- name: Copying Cuckoo startup scripts to Systemd [ 1 / 4 ]
  become: true
  become_method: sudo
  copy:
    src: "cuckoo_rooter.service"
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/cuckoo_rooter.service

- name: Copying Cuckoo startup scripts to Systemd [ 2 / 4 ]
  become: true
  become_method: sudo
  copy:
    src: "cuckoo.service"
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/cuckoo.service

- name: Copying Cuckoo startup scripts to Systemd [ 3 / 4 ]
  become: true
  become_method: sudo
  copy:
    src: "cuckoo_web.service"
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/cuckoo_web.service

- name: Copying Cuckoo startup scripts to Systemd [ 4 / 4 ]
  become: true
  become_method: sudo
  copy:
    src: "cuckoo_api.service"
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/cuckoo_api.service

- name: Starting and enabling Cuckoo systemd services [ 1 / 4 ]
  become: true
  become_method: sudo
  systemd:
    name: cuckoo_rooter.service
    state: started
    enabled: yes

- name: Starting and enabling Cuckoo systemd services [ 2 / 4 ]
  become: true
  become_method: sudo
  systemd:
    name: cuckoo.service
    state: started
    enabled: yes

- name: Starting and enabling Cuckoo systemd services [ 3 / 4 ]
  become: true
  become_method: sudo
  systemd:
    name: cuckoo_web.service
    state: started
    enabled: yes

- name: Starting and enabling Cuckoo systemd services [ 4 / 4 ]
  become: true
  become_method: sudo
  systemd:
    name: cuckoo_api.service
    state: started
    enabled: yes

- name: Set up done
  debug:
    msg: Set up is done, and Cuckoo is now started. Enjoy!
