os_packages:
  - python
  - python-pip
  - python-dev
  - libffi-dev
  - libssl-dev
  - libcap2-bin
  - python-virtualenv
  - python-setuptools
  - tcpdump
  - apparmor-utils
  - libjpeg-dev
  - zlib1g-dev
  - swig
  - python-libvirt
  - python-libvirt
  - libfuzzy-dev
  - ssdeep
  - python3-pip
  - mongodb
  - postgresql
  - libpq-dev
  - libguac-client-vnc0
  - libguac-client-ssh0
  - guacd
  - automake
  - libtool
  - make
  - gcc
  - flex
  - bison
  - libssl-dev
  - libjansson-dev
  - libmagic-dev
  - libjson-perl
  - libyaml-dev
  - libcommon-sense-perl
  - libjson-xs-perl
  - libtypes-serialiser-perl
  - libyaml-doc
  - openvpn
  - iptables-persistent
  - openjdk-8-jdk
  - net-tools
  - ethtool
  - curl
